# プロジェクト名
name: torippy
# バンドルID
options:
  # バンドルプレフィックス
  bundleIdPrefix: com.dev.torippy
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja
  
# ターゲットごとの設定
targets:
  torippy:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "17.0"
    sources:
      - torippy
    info:
      path: torippy/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: XXXXXXXXXX
